  server:
  port: 9060

spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true

      routes:
      - id: order-service-route
        uri: lb://order-service
        predicates:
        - Path=/order/**
        filters:
        - RewritePath=/order/(?<segment>.*), /$\{segment}

      - id: delivery-service-route
        uri: lb://delivery-service
        predicates:
        - Path=/delivery/**
        filters:
        - RewritePath=/delivery/(?<segment>.*), /$\{segment}
        
      - id: product-service-route
        uri: lb://product-service
        predicates:
        - Path=/product/**
        filters:
        - RewritePath=/product/(?<segment>.*), /$\{segment}
